version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-job:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: create env var
          command: |
            echo "GITHUB_PAT=${GITHUB_PAT}" >> .env
            echo "GITHUB_APP_ID=${GITHUB_APP_ID}" >> .env
            echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env
            echo "GITHUB_APP_PEM=${GITHUB_APP_PEM}" >> .env
      - run:
          name: Run create pr from issue
          command: poetry run pytest tests/e2e
      - store_test_results:
          path: junit.xml

workflows:
  build-and-test:
    jobs:
      - test-job
