name: Cypress E2E Tests

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'sweepai/**'
      - 'sweep_chat/**'
      - pyproject.toml
      - requirements.txt

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install npm dependencies
      working-directory: sweep_chat
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Cache next build
      uses: actions/cache@v4
      with:
        path: ./sweep_chat/.next
        key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-next-
    
    - name: Build next.js
      working-directory: sweep_chat
      if: steps.cache-next-build.outputs.cache-hit != 'true'
      run: npm run build

    - name: Load .env.local from secrets
      working-directory: sweep_chat
      run: |
        echo "${{ secrets.CYPRESS_ENV_LOCAL }}" > .env.local
        echo "${{ secrets.CYPRESS_ENV_JSON }}" > cypress.env.json
    
    - name: Run Cypress tests
      working-directory: sweep_chat
      run: npm run e2e:ci
