name: Cypress E2E Tests

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'sweepai/**'
      - 'sweep_chat/**'
      - pyproject.toml
      - requirements.txt

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.npm
          sweep_chat/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('sweep_chat/**/*.js', 'sweep_chat/**/*.jsx', 'sweep_chat/**/*.ts', 'sweep_chat/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    
    - name: Install npm dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      working-directory: sweep_chat
      run: npm ci

    - name: Build next.js
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      working-directory: sweep_chat
      run: npm run build

    - name: Cache save node modules
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.npm
          sweep_chat/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('sweep_chat/**/*.js', 'sweep_chat/**/*.jsx', 'sweep_chat/**/*.ts', 'sweep_chat/**/*.tsx') }}

    - name: Load .env.local from secrets
      working-directory: sweep_chat
      run: |
        echo "${{ secrets.CYPRESS_ENV_LOCAL }}" > .env.local
        echo "${{ secrets.CYPRESS_ENV_JSON }}" > cypress.env.json
        ls -la
    
    - name: Run Cypress tests
      working-directory: sweep_chat
      run: npm run e2e:ci
