name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        browser: [chrome, firefox, safari]
        node: [18, 20, 21]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Write to .env
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> platform/.env
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
          browser: ${{ matrix.browser }}
          wait-on: 'http://localhost:3000' # Waits for above
          record: true
          working-directory: platform
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}


# jobs:
#   install:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Write to .env
#         run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> platform/.env

#       - name: Cypress install
#         uses: cypress-io/github-action@v6
#         with:
#           # Disable running of tests within install job
#           runTests: false
#           build: npm run build
#           working-directory: platform

#       - name: Save build folder
#         uses: actions/upload-artifact@v4
#         with:
#           name: build
#           if-no-files-found: error
#           path: build
#           working-directory: platform

#   cypress-run:
#     runs-on: ubuntu-22.04
#     needs: install
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Download the build folder
#         uses: actions/download-artifact@v4
#         with:
#           name: build
#           path: build

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           start: npm start
#           browser: chrome
