name: Pylint

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  pylint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add Poetry to PATH (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="/Users/runner/.local/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      - name: Run pylint
        run: poetry run pylint sweepai --errors-only
